In [18]:
import numpy as np
import os

alignment_dir = 'results/alignment/minhuh/prh/val/language_pool-avg_prompt-False_language_pool-avg_prompt-False/'

for filename in os.listdir(alignment_dir):
    fp = os.path.join(alignment_dir, filename)
    print(f"\nFile: {filename}")
    result = np.load(fp, allow_pickle=True).item()
    for key in result.keys():
        print(f"{key}:", result[key])
        print(result[key].shape)


File: cycle_knn_k10.npy
scores: [[0.95117188 0.92480469]
 [0.9296875  0.94824219]]
(2, 2)
indices: [[[23. 23.]
  [-1. -1.]]

 [[19. -1.]
  [21. 20.]]]
(2, 2, 2)

File: cka.npy
scores: [[1.0000031  0.93485945]
 [0.93485945 1.00000203]]
(2, 2)
indices: [[[22. 22.]
  [12. 13.]]

 [[13. 12.]
  [22. 22.]]]
(2, 2, 2)

File: all_alignment_mutual_knn_k10.npy
all_alignments: [[1.         0.25839844 0.27089846 ... 0.15058595 0.14541015 0.13662109]
 [0.25839844 1.         0.52158201 ... 0.16220704 0.15976563 0.1584961 ]
 [0.27089846 0.52158201 1.         ... 0.18730468 0.18603516 0.18779299]
 ...
 [0.15058595 0.16220704 0.18730468 ... 1.         0.86318362 0.54140627]
 [0.14541015 0.15976563 0.18603516 ... 0.86318362 1.         0.59746093]
 [0.13662109 0.1584961  0.18779299 ... 0.54140627 0.59746093 1.        ]]
(81, 81)

File: unbiased_cka.npy
scores: [[0.99979562 0.92984909]
 [0.92984909 0.99981648]]
(2, 2)
indices: [[[23. 23.]
  [12. 13.]]

 [[13. 12.]
  [23. 23.]]]
(2, 2, 2)

File: svcca.npy

In [19]:
import numpy as np

# Load and print the all alignments file
alignment_file = os.path.join(alignment_dir, 'all_alignment_mutual_knn_k10.npy')
result = np.load(alignment_file, allow_pickle=True).item()

print("\nAll alignments file contents:")
for key, value in result.items():
    print(f"\n{key}:")
    print(value)
    print(f"Shape: {value.shape}")



All alignments file contents:

all_alignments:
[[1.         0.25839844 0.27089846 ... 0.15058595 0.14541015 0.13662109]
 [0.25839844 1.         0.52158201 ... 0.16220704 0.15976563 0.1584961 ]
 [0.27089846 0.52158201 1.         ... 0.18730468 0.18603516 0.18779299]
 ...
 [0.15058595 0.16220704 0.18730468 ... 1.         0.86318362 0.54140627]
 [0.14541015 0.15976563 0.18603516 ... 0.86318362 1.         0.59746093]
 [0.13662109 0.1584961  0.18779299 ... 0.54140627 0.59746093 1.        ]]
Shape: (81, 81)


In [22]:
import numpy as np
import os
import pickle

alignment_file = os.path.join(alignment_dir, 'mutual_knn_k10.pkl')
with open(alignment_file, 'rb') as f:
    result = pickle.load(f)

print("\nMutual KNN k=10 file contents:")
for key, value in result.items():
    print(f"\n{key}:")
    print(value)
    print(f"Shape: {value.shape if hasattr(value, 'shape') else len(value)}")



Mutual KNN k=10 file contents:

(0, 0):
[[1.         0.41474611 0.32197267 0.28789061 0.24023438 0.20576173
  0.18916015 0.17138672 0.15546875 0.14433594 0.13222656 0.13164063
  0.12832031 0.12363282 0.12353516 0.11855469 0.12060547 0.11582032
  0.1116211  0.11171875 0.10683594 0.10224609 0.09863281 0.09433594
  0.09082031]
 [0.41474611 1.         0.66435546 0.57968748 0.49013671 0.39960939
  0.3636719  0.33232424 0.31396484 0.29462892 0.27197266 0.26513672
  0.25312501 0.24296875 0.23808593 0.23105469 0.22841796 0.21884766
  0.21113282 0.20527345 0.19511719 0.18583985 0.17666017 0.16816406
  0.16298828]
 [0.32197267 0.66435546 1.         0.77050781 0.63701177 0.51640618
  0.46748048 0.4227539  0.39267579 0.36406249 0.33749998 0.32910156
  0.31269532 0.30126953 0.29560548 0.28349611 0.28115234 0.27011719
  0.26064456 0.25400394 0.24306642 0.22968751 0.21845704 0.20898438
  0.20029297]
 [0.28789061 0.57968748 0.77050781 1.         0.7464844  0.59013671
  0.52382815 0.47167969 0.4385741