In [14]:
import numpy as np
import os

alignment_dir = 'results/alignment/minhuh/prh/val/language_pool-avg_prompt-False_language_pool-avg_prompt-False/'

for filename in os.listdir(alignment_dir):
    fp = os.path.join(alignment_dir, filename)
    print(f"\nFile: {filename}")
    result = np.load(fp, allow_pickle=True).item()
    for key in result.keys():
        print(f"{key}:", result[key])


File: cycle_knn_k10.npy
scores: [[0.95117188 0.92480469]
 [0.9296875  0.94824219]]
indices: [[[23. 23.]
  [-1. -1.]]

 [[19. -1.]
  [21. 20.]]]

File: cka.npy
scores: [[1.0000031  0.93485945]
 [0.93485945 1.00000203]]
indices: [[[22. 22.]
  [12. 13.]]

 [[13. 12.]
  [22. 22.]]]

File: unbiased_cka.npy
scores: [[0.99979562 0.92984909]
 [0.92984909 0.99981648]]
indices: [[[23. 23.]
  [12. 13.]]

 [[13. 12.]
  [23. 23.]]]

File: svcca.npy
scores: [[0.8550464  0.82115573]
 [0.82115573 0.88534151]]
indices: [[[24. 24.]
  [12. 14.]]

 [[14. 12.]
  [13. 14.]]]

File: mutual_knn_k10.npy
scores: [[1.         0.64228523]
 [0.64228523 1.        ]]
indices: [[[-1. -1.]
  [-1. -1.]]

 [[-1. -1.]
  [-1. -1.]]]
